import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";
import Head from "next/head";


const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900' ], // Add the weights you need here
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head><link rel="icon" href="/favicon.ico" /></Head>
      <body className={poppins.className}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
